# Dev Profile Configuration

# PostgreSQL (Local Docker / Neon)
spring.datasource.url=jdbc:postgresql://localhost:5432/leave_approval_db
spring.datasource.username=postgres
spring.datasource.password=postgres

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Camunda
camunda.bpm.database.schema-update=true
